# Generated by Django 5.1.5 on 2025-01-17 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentDesk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='id_grupo',
        ),
        migrations.AlterField(
            model_name='teams',
            name='team',
            field=models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software'), ('NW', 'Red o Internet'), ('SG', 'Seguridad'), ('OT', 'Otro')], max_length=20, verbose_name='Team'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='state',
            field=models.CharField(choices=[('NEW', 'Nuevo'), ('IN_PROGRESS', 'En progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='NEW', max_length=20, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='type_error',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='AgentDesk.teams', verbose_name='Tipo de error'),
        ),
    ]
