# Generated by Django 5.1.5 on 2025-01-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AgentDesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profiles',
        ),
    ]
