# Generated by Django 5.1.5 on 2025-01-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentDesk', '0002_remove_tickets_id_grupo_alter_teams_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='team',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Red o Internet', 'Red o Internet'), ('Seguridad', 'Seguridad'), ('Otro', 'Otro')], max_length=20, verbose_name='Team'),
        ),
    ]
